on:
  schedule:
    - cron: '0 0 * * *' # every day at midnight

permissions:
  contents: read
  packages: write
    
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            docker.io/unstoppablemango/mage-server
            ghcr.io/unstoppablemango/mage-server
          tags: |
            type=raw,value=nightly
            type=raw,value=upstream-main
            type=semver,pattern={{major}}.{{minor}}-nightly
            type=semver,pattern={{major}}-nightly
            type=sha

      - uses: docker/login-action@v3
        with:
          username: unstoppablemango
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          build-args: UPSTREAM_VERSION=main
          platforms: ${{ github.event_name == 'pull_request' && 'linux/amd64' || 'linux/amd64,linux/arm64' }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          provenance: true
          sbom: true
